services:
  app:
    build: .
    expose:
      - "80"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - gov-ai-admin-net
      - easypanel

networks:
  gov-ai-admin-net:
    name: gov-ai-admin-net
    ipam:
      config:
        - subnet: 10.200.187.0/24
  easypanel:
    external: true
